# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GLLoopViewDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Kingfisher', '~> 3.10.0'

  # Pods for GLLoopViewDemo

end
